server:
  port: 8082
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.postgresql.Driver
    #    cooper's database
    url: jdbc:postgresql://localhost:5432/cs309_ooad?serverTimezone=GMT%2b8
    username: postgres
    password: 1234
  #    url: jdbc:postgresql://localhost:5432/spring_project
  #    username: postgres
  #    password: 2333
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true


# Logger Config
logging:
  level:
    cs309_dorm_backend: debug

